# Site settings
title: AMBIL HIKMAHNYA
email: aquaberrry@gmail.com
url: https://example.github.io
description: "Aquaberry adalah web pembelajara tentang mata kuliah application mobile. Mari kita ambil hikmahnya."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: AQUABERRY | AMBIL HIKMAHNYA @ 2016

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/piwclothing
  - title: facebook
    url: https://www.facebook.com/piwclothingofficial
  - title: blog
    url: http://www.piwofficial.blogspot.co.id
  - title: github
    url: https://github.com/apmobgalery14

# Build settings
markdown: kramdown
permalink: pretty
