# Site settings
title: Aquaberry
email: aquaberrry@gmail.com
url: https://aquaberrry.github.io
description: "Aquaberry adalah web musik yang di sediakan untuk anda semua yang mengakses website kami."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Aquaberry Web Music Store

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rianaries1
  - title: facebook
    url: https://facebook.com/rianariefani
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://aquaberrry.github.io

# Build settings
markdown: kramdown
permalink: pretty
